---
kind: "operation"
client: "rug-cli 0.17.1"
editor:
  name: "atomist-rugs.travis-editors.EnableTravisForRugArchiveDSL"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.4.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "ffa56d6"
  parameters:
    - "repo_slug": "atomist-rugs/spring-boot-editors"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

---
kind: "operation"
client: "rug-cli 0.21.3"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScript"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.5.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "a94e3ae"

---
kind: "operation"
client: "rug-cli 0.21.3"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScript"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.5.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "75d5b21"

